### PR TITLE
update error handling

### PR DESCRIPTION
**Pull request by rccsousa**
Adresses Issue #19 

Why: 
- `fetchDoc` had poor error handling, which was being performed when the function was call on the different content pages;
How:
- added a try/catch block to `fetchDoc` to ensure error handling inside the function;

### CODE REVIEW

**Comment by davelange** [comment]
Just noticed you have this part
```
if (draft) {
    const { cookies } = await import('next/headers')
    token = cookies().get(payloadToken)
 }
```
Is this to allow viewing drafts as posted, when logged in?

**Comment by rccsousa** [comment]
> Just noticed you have this part
> 
> ```
> if (draft) {
>     const { cookies } = await import('next/headers')
>     token = cookies().get(payloadToken)
>  }
> ```
> 
> Is this to allow viewing drafts as posted, when logged in?

@davelange precisely. This will be used upon the implementation "Preview" and "Live Preview" 
Since fetchDoc came bundled with Payload and is being recycled some bits and pieces are still not being used in the current version of what we're implementing here.

**Comment by davelange** [comment]
Regarding type safety, how are you planning on using the function? I see it receives a generic, but it's not defined anywhere yet

**Comment by rccsousa** [comment]
from my understanding the function receives a generic but then is controlled via the `collection` argument. 
i wasn't the one who implement it at first but what makes the most sense to me is that it was built this way to ensure keep it flexible as available collections change. 

would it make more sense to declare `interface` to "lock" it to `Blogpost`, `PodcastEpisode` and so on?

**Comment by rccsousa** [comment]
updated typing as discussed 🙇

**Review by davelange — APPROVED** [review]

**Pull request merged**
